version: "2"
services:
  app:
    container_name: refugee
    image: deakinlaunchpad/refugee-frontend-dev:test
    restart: always
    environment:
      - NODE_ENV=test
      - DEBUG=app:*,-app:nDispatcher:REMOVED
    command: bash -c "node setup.js && nodemon src/server.js"
    ports:
      - "3026:3026"
    links:
      - mongo_refugee_test
      - redis_refugee_test
  mongo_refugee_test:
    container_name: mongo_refugee_test
    image: mongo
    volumes:
      - ./data:/data/refugee-test/db
    ports:
      - "27017:27017"
  redis_refugee_test:
    container_name: redis_refugee_test
    image: redis
    ports:
      - "6379:6379"